//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaYanna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> PizzaID { get; set; }
        public Nullable<int> PizzaAmount { get; set; }
        public int UserID { get; set; }
        public Nullable<int> DrinkID { get; set; }
        public Nullable<int> DrinkAmount { get; set; }
        public Nullable<int> DessertID { get; set; }
        public Nullable<int> DessertAmount { get; set; }
        public Nullable<double> PromoPercent { get; set; }
    
        public virtual Dessert Dessert { get; set; }
        public virtual Drink Drink { get; set; }
        public virtual Pizza Pizza { get; set; }
        public virtual User User { get; set; }
    }
}
