//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaYanna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo
    {
        public int PromoID { get; set; }
        public string PromoCode { get; set; }
        public double PromoPercent { get; set; }
        public string ItemName { get; set; }
        public string ItemSize { get; set; }
        public string ItemType { get; set; }
        public string ItemDeadline { get; set; }
    }
}
