//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaYanna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsText
    {
        public int PromoTextID { get; set; }
        public string PromoText { get; set; }
    }
}
